# R conformance fixture for the numeric core of `src/helpers.ts`.
#
# This is NOT one of the ported goldens. Every other fixture under
# `tests/fixtures/` was generated by the py port's `generate_fixtures.R` and is
# copied here, never regenerated (see `.claude/CLAUDE.md`). This one is
# generated here, by this script, because it pins R's *arithmetic* rather than
# seminrExtras' output: which of R's three means a routine follows.
#
# R has three means and they are different C routines:
#
#   mean.default    summary.c  do_mean    sum/n, then a correcting second pass
#   var / sd        cov.c      MEAN macro the same body as do_mean
#   colMeans        array.c    do_colsum  one pass, no correction
#
# The seed is not arbitrary. It was chosen by sweeping seeds 1..4000 for a
# vector on which all four discriminations hold at once:
#
#   - the two-pass mean is bit-identical to R's `mean(x)`
#   - the plain `sum(x)/n` is NOT (3.47 ulp out)
#   - `sd` centred on the two-pass mean is bit-identical to R's `sd(x)`
#   - `sd` centred on the plain mean is NOT (1.88 ulp out)
#
# Without that last pair the test cannot tell a correct `rSd` from the one this
# package shipped through v0.1.1, which centred on the uncorrected mean.
#
# R's LDOUBLE accumulators are plain doubles on arm64 macOS
# (`capabilities("long.double")` is FALSE), which is what makes every value
# here reproducible in float64 TypeScript. On a platform with 80-bit long
# doubles these would not be bit-reproducible and the test would have to fall
# back to a tolerance.
#
# Regenerate with:  Rscript tests/fixtures/helpers/arith.R

seed <- 3255
set.seed(seed)
x <- runif(97, -500, 500)

set.seed(seed + 1)
m <- matrix(runif(97 * 3, -500, 500), nrow = 97, ncol = 3)

g <- function(v) paste(sprintf("%.17g", v), collapse = ", ")

out <- c(
  "{",
  sprintf('  "generator": "tests/fixtures/helpers/arith.R",'),
  sprintf('  "rVersion": "%s",', paste(R.version$major, R.version$minor, sep = ".")),
  sprintf('  "longDouble": %s,', tolower(as.character(capabilities("long.double")))),
  sprintf('  "seed": %d,', seed),
  sprintf('  "x": [%s],', g(x)),
  sprintf('  "mean": %s,', sprintf("%.17g", mean(x))),
  sprintf('  "sd": %s,', sprintf("%.17g", sd(x))),
  sprintf('  "var": %s,', sprintf("%.17g", var(x))),
  sprintf('  "mat": [%s],', paste(apply(m, 1, function(r) paste0("[", g(r), "]")), collapse = ", ")),
  sprintf('  "colMeans": [%s],', g(colMeans(m))),
  sprintf('  "colSds": [%s]', g(apply(m, 2, sd))),
  "}"
)

# Write next to this script, wherever it was invoked from.
args <- commandArgs(trailingOnly = FALSE)
here <- dirname(sub("^--file=", "", args[grep("^--file=", args)][1]))
writeLines(out, file.path(here, "arith.json"))
