/**
 * Load the R-generated golden fixtures and compare matrices at parity tolerances.
 *
 * Ported from `../seminrExtras-py/tests/helpers/fixtures.py`. The loader decodes
 * the row-major `{rows, cols, values}` matrix nodes (re-boxing jsonlite's
 * `auto_unbox` collapse of length-1 vectors, mapping R `NA` -> `NaN`) into
 * `@seminr/core`'s `NamedMatrix`.
 *
 * Baseline model goldens live under `tests/fixtures/models/<ID>.json` and were
 * generated by `../seminrExtras-py/scripts/generate_fixtures.R` (the only
 * generator). Later feature slices add their own loaders alongside these.
 *
 * Label alignment: `expectNamedClose` aligns by row and column *labels* where
 * they are shared (so a benign construct/indicator reordering between R and
 * seminr-ts never fails a test), and falls back to positional row comparison
 * when the row labels differ — the `rSquared` matrix is the one such case,
 * since seminr-ts names its rows `Rsq`/`AdjRsq` where R uses `R^2`/`AdjR^2`.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { namedMatrix, type NamedMatrix } from "@seminr/core";

// --- Tolerances -------------------------------------------------------------

/** All PLS quantities: per-cell absolute tolerance (plan acceptance bar). */
export const PLS_TOL = 1e-5;

// --- Paths ------------------------------------------------------------------

export const FIXTURES_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "fixtures");
export const MODELS_DIR = join(FIXTURES_DIR, "models");

// --- Fixture node decoding ---------------------------------------------------

/** A jsonlite-serialized named matrix, possibly collapsed by `auto_unbox`. */
export interface FixtureMatrixNode {
  rows?: string | string[] | null;
  cols?: string | string[] | null;
  values: unknown[];
}

/** A `tests/fixtures/models/<ID>.json` golden. */
export interface ModelFixture {
  id: string;
  dataset: string;
  description: string;
  pathCoef: FixtureMatrixNode;
  outerWeights: FixtureMatrixNode;
  rSquared: FixtureMatrixNode;
  [key: string]: unknown;
}

function isNumber(x: unknown): x is number {
  return typeof x === "number";
}

/** R `NA` arrives as JSON `null` or the string `"NA"`. */
function cell(x: unknown): number {
  if (x === null || x === undefined || x === "NA") return NaN;
  return x as number;
}

function nameList(names: string | string[] | null | undefined, n: number): string[] {
  if (typeof names === "string") return [names];
  if (names != null) return [...names];
  return Array.from({ length: n }, (_, i) => String(i));
}

/**
 * Undo jsonlite `auto_unbox`: re-inflate scalar names and collapsed vectors.
 *
 * A length-1 vector becomes a bare scalar, so a single-row / single-column
 * matrix loses a dimension (e.g. a one-endogenous-construct `rSquared` or a
 * single-item construct's weights).
 */
function rebox(node: FixtureMatrixNode): { rows: string[]; cols: string[]; values: unknown[][] } {
  const raw = node.values;
  let values2d: unknown[][];
  if (raw.length > 0 && isNumber(raw[0])) {
    // Whole matrix collapsed to a flat vector: one scalar per row (k x 1).
    values2d = raw.map((v) => [v]);
  } else {
    values2d = raw.map((row) => (isNumber(row) ? [row] : [...(row as unknown[])]));
  }
  const nCols = values2d.length > 0 ? values2d[0]!.length : 0;
  return {
    rows: nameList(node.rows, values2d.length),
    cols: nameList(node.cols, nCols),
    values: values2d,
  };
}

/** Decode a `{rows, cols, values}` fixture node into a `NamedMatrix`. */
export function toMatrix(node: FixtureMatrixNode): NamedMatrix {
  const { rows, cols, values } = rebox(node);
  const decoded = values.map((row) => row.map(cell));
  const nCols = decoded.length > 0 ? decoded[0]!.length : cols.length;
  if (decoded.length !== rows.length || nCols !== cols.length) {
    throw new Error(
      `decoded matrix shape (${decoded.length}, ${nCols}) does not match names ` +
        `(${rows.length} rows, ${cols.length} cols)`,
    );
  }
  return namedMatrix(rows, cols, decoded);
}

/**
 * Parse `tests/fixtures/models/<modelId>.json`.
 *
 * Throws if the golden is missing (fixtures are committed; a miss means a
 * typo'd ID or an incomplete fixture copy).
 */
export function loadModelFixture(modelId: string): ModelFixture {
  const text = readFileSync(join(MODELS_DIR, `${modelId}.json`), "utf8");
  return JSON.parse(text) as ModelFixture;
}

// --- Comparison ---------------------------------------------------------------

/**
 * Assert `actual` matches `expected` within `tolerance`, aligning by label.
 *
 * Columns are aligned by label (the two column-label sets must be equal). Rows
 * are aligned by label when the row-label sets are equal, else compared
 * positionally (equal row counts required) — this is the `rSquared` case,
 * where seminr-ts's `Rsq`/`AdjRsq` rows carry R's `R^2`/`AdjR^2` values in the
 * same order. Any `NaN` cell must match a `NaN` on the other side.
 */
export function expectNamedClose(
  actual: NamedMatrix,
  expected: NamedMatrix,
  tolerance: number = PLS_TOL,
  label: string = "",
): void {
  const a = actual.values;
  const e = expected.values;
  const aShape = [a.length, a[0]?.length ?? 0];
  const eShape = [e.length, e[0]?.length ?? 0];
  if (aShape[0] !== eShape[0] || aShape[1] !== eShape[1]) {
    throw new Error(
      `${label}: shape (${aShape}) != expected (${eShape}) ` +
        `(actual ${actual.rows}x${actual.cols} vs expected ${expected.rows}x${expected.cols})`,
    );
  }

  const sameSet = (x: string[], y: string[]) =>
    x.length === y.length && new Set(x).size === new Set([...x, ...y]).size;

  if (!sameSet(actual.cols, expected.cols)) {
    throw new Error(`${label}: column labels differ: ${actual.cols} vs ${expected.cols}`);
  }
  const colMap = expected.cols.map((c) => actual.cols.indexOf(c));

  const rowMap = sameSet(actual.rows, expected.rows)
    ? expected.rows.map((r) => actual.rows.indexOf(r))
    : expected.rows.map((_, i) => i); // Positional fallback (rSquared: Rsq/AdjRsq vs R^2/AdjR^2).

  for (let i = 0; i < expected.rows.length; i++) {
    for (let j = 0; j < expected.cols.length; j++) {
      const got = a[rowMap[i]!]![colMap[j]!]!;
      const ref = e[i]![j]!;
      const cellLabel = `${label}[${expected.rows[i]}, ${expected.cols[j]}]`;
      if (Number.isNaN(ref)) {
        if (!Number.isNaN(got)) throw new Error(`${cellLabel}: got ${got}, expected NA`);
      } else if (Number.isNaN(got) || Math.abs(got - ref) > tolerance) {
        throw new Error(`${cellLabel}: got ${got}, expected ${ref} (|diff| > ${tolerance})`);
      }
    }
  }
}
